### ISSUE TITLE
Booking.com request 

### ISSUE THREAD

**Issue by Hagsten** [tykeal/homeassistant-rental-control#102]
Hi! 

First I want to thank you for a great integration! I have my property on both booking and Airbnb but it seems that there are issues using this integration with Booking - is there any plans on adding booking as a supported vendor?

Thanks 🙏🙂

**Comment by tykeal** [comment]
First, what seems to be the issue with Booking? If it's pulling bad information from the iCal that would be because I don't currently have access to any Booking.com iCal URLs to look at and figure out what's different from the other platforms I'm explicitly coding for. If it's an access issue, the integration currently only supports publicly available iCal feeds. I don't have access to any private feeds so that would be work that needs to be done by parties that do have that access and are interested in it ;)

There's two ways forward here:

1) If you feel you can do the work, send a patch with the needed changes. I'll work through code review with you to get it working
2) If you don't feel you can do the work yourself, you can provide me via a private message or email (tykeal@bardicgrove.org) a URL to a working Booking.com iCal feed.

**Comment by tykeal** [comment]
@Hagsten this feature is now in v0.7.5 which I released around 2 hours ago.

Making this feature highlighted that the VRBO handling was broken and has been for a bit as it was partly related to the booking.com calendar not working.
