### ISSUE TITLE
Change title of invite to guest name or template?

### ISSUE THREAD

**Issue by joestump** [tykeal/homeassistant-rental-control#188]
@tykeal thank you for this integration! I'm using Atomic Calendar Revive to show upcoming check-ins and I'd like to leverage some of it's functionality. 

Namely:

* A way to change the event title from `Reserved` to the guest's name.
* Atomic Calendar Revive will link links in title; could possibly wrap the title in a link to the reservation?
* Maybe allow people to configure title via a template?

If you want to point me at where I could introduce this functionality, I'd be willing to take a crack at it.

**Comment by tykeal** [comment]
@joestump input from users of for configuration would be done via the [config_flow.py](https://github.com/tykeal/homeassistant-rental-control/blob/main/custom_components/rental_control/config_flow.py). The schema that is consumed by the config_flow is defined in part by the [async_migrate_entry](https://github.com/tykeal/homeassistant-rental-control/blob/main/custom_components/rental_control/__init__.py#L187) of __init__.py

The calendar bits are handled by way of the [calendar.py](https://github.com/tykeal/homeassistant-rental-control/blob/main/custom_components/rental_control/calendar.py) and the parsing of the icals is handled by [_ical_parser](https://github.com/tykeal/homeassistant-rental-control/blob/main/custom_components/rental_control/__init__.py#L572) and [_ical_event](https://github.com/tykeal/homeassistant-rental-control/blob/main/custom_components/rental_control/__init__.py#L663) functions

The event sensors are all managed by way of the (poorly named) [calsensor.py](https://github.com/tykeal/homeassistant-rental-control/blob/main/custom_components/rental_control/sensors/calsensor.py) and consume the calendar object from the main integration itself (which is also consumed by the calendar calendar entity previously mentioned.

Now, that that is all out of the way. I'm more than happy to see PRs come in, but I do want to caution, that I don't want to see changes that make it such that folks must use Atomic Calendar Revive to use this!

Finally, on the `Reserved` vs guests name. If you're using Airbnb then you will never get the guests name from your calendar unless you're using a third-party integrator like Guesty or similar. At best, you'll get the reservation ID. I don't change the event summary (aka title) to that because using `Reserved` is something a lot easier to look at visually. In any case, you can look over the logic of it all to see how it's being handled. But if it's showing up `Reserved` there's like a good reason ;)

**Comment by joestump** [comment]
@tykeal oh, easy - switched over to my Host Tool `ics` URL and it works perfectly now. I've updated my PR to add a FAQ with these details and how to get the `ics` URLs from a few providers. Closing this out now.

**Comment by refazi** [comment]
i'm not that familer with homeassist but would like to understand how can i have this integration show and extract the guest name from the calendar so it can be used for sending it to a display that will display the name of the guest without me going in manually every time and changing it, is there an easy way to make few configuration changes to one of the components of this plugin to enhance it?

**Comment by tykeal** [comment]
@refazi first, your commenting on an issue that is months old. You're lucky I noticed the email about it!

second, if the platform you are using doesn't provide the information in the ICS there is nothing that RC will be able to do for you. For instance, Airbnb does _not_ provide guest names, they only provide the booking ID _unless_ you're using one of their partner channel manager platforms like Guesty, but even then, you're not using the Airbnb ICS but the Guesty one at that point.

So, it really depends upon your platform.

Myself, all of my properties are on Airbnb only, I just suffer with booking IDs, at least they're always unique.

If the platform _does_ provide the information for you, then it will be extracted into the `Slot name` attribute of the sensor and you can do with that whatever you want.

**Comment by refazi** [comment]
thank you for your reply, it looks like they made this change in 2019, good to know.
the new smart lock via airbnb integration has  the guest first name in them, maybe there is a good way to scub it from the lock integration? 
I am also hosting exclusively on Airbnb and currently using August/Yale, any chance we can hit that direction in an easy way ?

**Comment by tykeal** [comment]
If Airbnb doesn't put it into the ICS there is no way to get the data. They're extremely closed around their API so unless you're a big platform partner there's no way to get the data you're asking for without them putting it into the ICS. It _used_ to be in there about 4 years ago but they removed it due to PII security concerns since the ICS URLs require no authentication.
