### ISSUE TITLE
Connect to booking.com?

### ISSUE THREAD

**Issue by elji-lennart** [tykeal/homeassistant-rental-control#217]
How can I connect to booking.com?

**Comment by tykeal** [comment]
Please lookup how to get an iCal URL from booking.com. I personally do not operate off of booking.com and the support that is in the integration is purely because of community members that use the integration providing me a URL to look over to make sure that I could properly identify the format of events.

A quick search on `booking.com host ical url` turns up the [this](https://partner.booking.com/en-us/help/rates-availability/extranet-calendar/syncing-your-bookingcom-calendar-third-party-calendars) page and [this](https://help.nomadstays.com/898937-How-to-Find-your-iCal-on-Bookingcom) page which hopefully will lead you in the correct direction.
