### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by IanAdd** [tykeal/homeassistant-rental-control#51]
I've removed keymaster and your early version and used HACS as suggested.
That went smoothly.

Adding integration fails with 'config flow could not be loaded'.

In my previous attempt this was solved by installing Keymaster, but you have indicated that keymaster is no longer required so trying to leave it out.

**Comment by IanAdd** [comment]
However on 2nd attempt the dialog box came up ok.

**Comment by tykeal** [comment]
@IanAdd Thanks, I'll try to repro this in my test instance.

**Comment by IanAdd** [comment]
Little thought... When entry / amendment of config items is made I think a restart is required?. If possible, prompt user if the change made does require a restart.

**Comment by tykeal** [comment]
A restart shouldn't have been needed, however, forcing a refresh of the integration page is recommended. I don't really have a good way of saying you need to do that, at least not until I have a Changelog working correctly.

You're still getting my early alpha's here so there's likely something related to that. I can't get it to repo on my test instance even after completely purging the integration from the system

**Comment by tykeal** [comment]
Well, let's put it this way, per HACS any update to the integration from the install perspective should need a restart of HA. I'm using config flow only so in theory a restart of HA shouldn't be needed. But in actuality it probably is. HACS does, however tell you that you need to restart....

The more significant issue is likely due to the change in options and therefore the configuration flow screen. Your original screen was probably cached and so it caused an error when you tried to make changes. Forcing a full refresh (ctrl+shift+r) of the integration configuration screen should resolve that as it will purge the caches

**Comment by IanAdd** [comment]
Let's ignore that quirky install.
My thought was that if I changed the number of events then entities needed to be created or deleted. This I thought would need a restart, maybe I just needed to refresh screen.
Let's close this.
