### ISSUE TITLE
Entities and attributes

### ISSUE THREAD

**Issue by IanAdd** [tykeal/homeassistant-rental-control#52]
with a Prefix set of AB
Using the entities card
An entity name shows as 'AB Airbnb (Not available)'
however a reservation entry shows 'AB Reserved'
Can I suggest 
a) dropping the 'Airbnb' if a prefix has been defined
b) adding the prefix to an entity which currently just says 'No reservation'

The repeating of the info in the entity attributes and the entity state is kind of confusing. I need to think this through before making suggestions.

Question...
if event_0 is the next / currently active event I assume event0 will be rewritten with event_1 info when the end date/time is in the past.
Is this triggered at checkout time? or when ?
is an entity possible for the just expired booking? eg to cater for late check-out request or for post departure correspondence ???

**Comment by IanAdd** [comment]
Andrew, I'd like to share some screenshots but would rather do it privately to you. No idea how in github.

**Comment by tykeal** [comment]
I'm confused by the request on dropping the Airbnb. There's no injection of that anywhere in the code unless you named your Rental Control entity as Airbnb.

For instance, I have 2 Airbnb calendars that I play with. For ease of use I add them to the system as their street number.

I name them thusly in my system:

H1 - 3713
H2 - 8301

With each set to generate 5 sensors, the entities that get created are as follows:

calendar.rental_control_h1_3713
sensor.rental_control_h1_3713_event_{0..4}

And similar for the H2 - 8301

So, what's happening is that the initial calendar name is used in creating the entities themselves. Nothing from that is injected into the event names.

Now, if you set a prefix the following happens:

The prefix is taken and as long as it isn't an empty string it is pre-pending to the event summary with an inserted space.

I like to set my prefix to something like 'H1 -' which then gets me events that look like 'H1 - Reserved', otherwise they just end up looking like 'Reserved'

On the question of the events. Yes, event_0 is the current, or up coming event. It expires out after the day is done. So, for instance, you have a guest that is checking out that morning, they will be currently in event_0 and event_1 should be the next event. So if they're checking in the same day you'll end up with event_0 being active in the morning and event_1 being active in the afternoon through the night. At midnight event_0 should be rewritten with event_1 and all the other ones will bump down an event.

The early checkin/checkout is going to come about once I have the lock code management actually working as Keymaster has start / stop times along with the date range (a feature I got added early last year). So this integration will be watching for changes to those for custom updates to the check-in/out that should be on the calendar. At least that's my intended workflow. I have  hard time justifying having extra in/out helpers when the intent is to manage the door locks too

**Comment by tykeal** [comment]
For sharing screenshots privately you could do one of a few things:

1) Create a private gist at https://gist.github.com/ and upload the shots there _or_ 
2) you can just email me here: tykeal@bardicgrove.org (it's in every single one of my commits ;) )

**Comment by IanAdd** [comment]
Ok, I have renamed my two calendars to be AB & TA and removed the prefixes. Rebooted HA for certainty.
Entity representing 'No Reservation' have no prefix so it doesn't show which calendar it came from, all the others have my chosen calendar name as a prefix.
This is an entities card.
![rc1](https://user-images.githubusercontent.com/10492213/150464397-58bcca7b-7a66-4f86-98e6-91b374e752b0.png)

**Comment by IanAdd** [comment]
thanks, will email for simplicity.

**Comment by tykeal** [comment]
I see what you're getting at. The **`Airbnb (Not available)`** is coming directly from Airbnb themselves. The code doesn't do any modifications of the summaries outside a prepend if defined.

To get rid of what you're seeing I would have to put in logic specifically to handle that and it would end up having to be special case for all platforms being specifically supported

**Comment by tykeal** [comment]
You're also correct that the **`No Reservation`** isn't doing a prepend. It's a devolved case because there aren't enough calendar entries to fill the sensor stack.

**Comment by IanAdd** [comment]
Just sent some screenshot by email.
Do ignore my aspirations unless you see benefit for yourself. I can work around what I see.

**Comment by tykeal** [comment]
Personally, don't have the event entities sitting around in cards. I have an Atomic Calendar card setup in agenda mode that I'm viewing directly. The sensors are more for automation and data holding / sharing with how I'm using or intending to use them.

I really should probably put a flow chart together on all of my current thoughts :D

**Comment by IanAdd** [comment]
I don't expect to use the entity card for the real work, just using as an easy way to grasp what your entities are up to.

I think the midnight entity repopulation cutover will be fine  However midnight needs to be the midnight of the timezone of the property not the HA though !!

**Comment by tykeal** [comment]
I don't currently have anything planned for allowing a TZ to be picked for a given entity. I'll welcome a PR.

The reason being that at least for my purposes, I'll be having an HA at each of the properties since I'm going to be driving the lock code set/unset from it and I use Z-Wave locks so I have to have the controller local to the lock.

I can totally understand the desire to hook this all up to a centrally managed HA as well to drive automation to multiple properties. However, in that case, I would be hooking up the remote HAs to my more "central" one and working through things that way.

**Comment by IanAdd** [comment]
I have a HA at the property and another local to me +11hrs different, I use the local to me one as a back up. My local one keeps an eye on the remote one via mqtt and takes over the heating (cloud based) if necessary. My code aims to be portable between the two using the difference to UTC to know which system it is running in. With your hard-coded entity swap at midnight it will not work for me unless you had a) an expired booking entity or b) a configurable offset.
Anyway you are making a great job of your project, well done.

**Comment by tykeal** [comment]
@IanAdd issue #55 is your TZ request. This is being fulfilled by PR #56

**Comment by tykeal** [comment]
I believe resolved the original asks, or at least explained why they aren't feasible.

* Calendars (and thereby the sensors) are now TZ aware
* **`No reservation`** is now properly prefixed if one is defined
* We are unable to scrub the redundant Airbnb out of the **`Airbnb (not available)`** or the TripAdvisor bookings due to the requirement for complex logic that would have to exist for any platform to do this sensibly

I'm willing to entertain PRs related to that last bullet point that would possibly allow for a custom "scrubbing" regular expression, but that would most assuredly be an advanced feature and personally I don't see the major benefit to it
