### ISSUE TITLE
Check Calendar less frequently

### ISSUE THREAD

**Issue by IanAdd** [tykeal/homeassistant-rental-control#79]
Can you add a facility to limit the frequency of retrieving information from a calendar? 
Or even a way to spot that you have that error and delay the next request for a suitable period??
I am getting 'Too many requests' error when accessing the same calendar by other means.

**Comment by tykeal** [comment]
I'm assuming this is your TripAdvisor calendar?

I'll try and cook up a way to add an additional limit. Right now the calendar is refreshed every ~2 minutes so roughly 720 times a day. Of the calendars I've gotten access to, TripAdvisor is the only one that seems to have this sort of API limit on the calendar pulls. The others may as well, but it's per IP and not per calendar!

For instance I know that AirBnB has a limit at a per IP level, but it's extremely high (something like 300 / minute / IP).

**Comment by IanAdd** [comment]
Thanks for considering this, It is Tripadvisor as you suspected. As yet I haven't found their limit.
I think it would be a great idea to recognise and react to the rejection of an attempt to update a calendar - perhaps like google mail does when losing internet connectivity where it polls less and less frequently until it succeeds again.

**Comment by tykeal** [comment]
It's going to have to be something that's semi-configurable. The issue with your suggestion is that the current design, and a design that does what you're stating, could still very easily exhaust the entire days access quota pretty rapidly. What will need to be done is for a user configurable option that specifies that maximum number of times per hour or day, to poll. The easy way on this would mean that when the integration reloads it would do a poll, so on HA restart, or if the integration was specifically reloaded. After that initial poll it would then only poll on a schedule based upon the configuration.

Current configuration works out to polling 30 times an hour (once every 2 minutes). If HA had it's way it would be 120 times an hour (every 30 seconds). So that's really the range to easily work inside of.

**Comment by IanAdd** [comment]
Based on what you say, i would set it no more than once an hour. However it would be great if i could trigger it manually on demand.

**Comment by tykeal** [comment]
My thoughts on implementation might not make it possible to just trigger it it manually. However, a reload of the particular integration would cause it.

So, let's say you've got 3 calendars configured. To force one of them to refresh you could go to Integrations -> Rental Control -> <the configured calendar> -> Tripple dot menu -> Reload.

This would cause that specific integration to unload temporarily and then reload itself, effectively resetting everything as if HA had just restarted and thereby forcing it to refetch the upstream calendar.

If I can figure out a good way. I may be able to come up with a way to manually trigger without doing that, but that's the quick and dirty way even now!

**Comment by tykeal** [comment]
@IanAdd just an FYI, I've closed this because the feature itself is complete. What doesn't exist is a callable method to trigger it. The refresh can be triggered in one of two ways at present:

1.  Reload the integration, but this causes all of the sensors to reload as well
1. Reconfigure the specific calendar integration and hit submit (no changes needed)

**Comment by IanAdd** [comment]
Thanks @tykeal I've reinstated my Tripadvisor calendar.

However the unavailable (not booked) entries have 'Not available' rather than 'calendar name (not available') which is what Airbnb shows. I seem to recall you had this tweaked before.
![rentalcontrol](https://user-images.githubusercontent.com/10492213/159099782-e23c2d84-9ae0-4470-a233-93e746bacd5d.png)

**Comment by IanAdd** [comment]
Actually, tripadvisor also seems to be missing some entries. Any chance an earlier edit got lost?

**Comment by tykeal** [comment]
The first issue is because you didn't set a calendar prefix. The second, is likely because you didn't scroll down in the configuration and uncheck **Ignore events that are not standard reservations** I do remember you asking for a way to keep all the non-reservation events and that's why the feature is in there.

Both issues can be resolved by reconfiguring the current calendar
