### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by Astogems** [tykeal/homeassistant-rental-control#99]
Hey, I like the idea of this Integration. I basically need to get it to work with Google Calendar. I am not using Zwave locks though. Is it still possible? When I key in my calender url https://calendar.google.com/calendar/u/0?cid=aXRAYXV0b2xpZmV0ZWNoLmNvbQ, it just shows unknown error.

**Comment by tykeal** [comment]
The calendar URL you gave is a private calendar. That would by why you're getting an error. The integration only accepts iCal files and as such, the URL that you've provided doesn't work as it's coming back as type HTML because it's a Google login screen. You would have to make the calendar public for the integration to accept it.

As to the locks... please note, that the integration doesn't actually manage the codes into the keymaster (yet, it's coming). Keymaster itself offically only works with ZWave locks, but I know that they've been doing work to get Zigbee locks working as well. Alternatively, if you aren't using Keymaster, then you just not specify a lock to the integration and you can code up your own automations around the sensors. I know a few folks that are using this integration do that.

**Comment by tykeal** [comment]
@Astogems I've provided guidance on how to get Google Calendars working with this integration in it's current incarnation here: https://community.home-assistant.io/t/custom-integration-rental-control-for-airbnb-vrbo-etc/383246/35?u=tykeal

I've got issue #129 open for a better way to handle generic calendars such as Google Calendars for folks that want to use this without being on a short term rental platform.
